
language: go
go:
  - 1.11.x
go_import_path: github.com/annymsMthd/go-modules-registry
sudo: true

script:
  - sudo apt-get --yes install snapd
  - sudo snap install gogitver
  - env GO111MODULE=on PATH=$PATH:/snap/bin make package

after_success:
  - bash <(curl -s https://codecov.io/bash)
